### ISSUE TITLE
Importer Repo aufräumen

### ISSUE THREAD

**Issue by cnoss** [lucascranach/importer#1]
Hi Jorge, ich habe dem Importer mal ein eigenes Repo verpasst. Könntest Du das ein bissl aufräumen? Ein wenig hab ich das schon gemacht, aber ich weiß nicht genau, was du brauchst. 

Danke!

**Comment by jhfpereira** [comment]
Ist nun etwas aufgeräumter. Habe dafür einige Ordner verschoben und umbenannt.

Ordnerstruktur

```
.
├── content
│   └── <XML-Exporte als Input>
├── documentation
│   ├── _stuff
│   └── structures
├── output
│   └── <JSON-Dateien als Output>
└── src
    ├── collectors
    ├── entities
    │   ├── graphic
    │   ├── graphicRestoration
    │   ├── literatureReference
    │   ├── main
    │   └── painting
    ├── exporters
    ├── importers
    │   └── inflators
    ├── postProcessors
    │   └── graphic
    └── process
```

Sofern noch nicht sauber genug, sollte ein neues Issue dafür erstellt werden.
