### ISSUE TITLE
BildUrl prüfen

### ISSUE THREAD

**Issue by cnoss** [lucascranach/importer#2]
Könntest Du bitte beim Importieren prüfen, ob auf dem Server ein Bild vorhanden ist und im JSON ein flag setzen? Das gilt sowohl für die Grafiken (Prio) als auch für die Gemälde. Bei den Grafiken gilt das für die virtuellen und realen Objekte.

**Comment by cnoss** [comment]
<img width="323" alt="Bildschirmfoto 2019-12-28 um 08 23 06" src="https://user-images.githubusercontent.com/2807738/71540469-82163180-294b-11ea-82f6-086baef549f0.png">

Die Grafiken sind immer mg «G» gepräfixt.

**Comment by cnoss** [comment]
Das Overall Image muss immer da sein.

**Comment by jhfpereira** [comment]
BildURL-Prüfung wird mit Commit 090d034050001072c52f4c461898b9e799c0e660 eingeführt.
