### ISSUE TITLE
Das Feld exhibitionHistory bitte umbennen …

### ISSUE THREAD

**Issue by cnoss** [lucascranach/importer#6]
… in representativeObject

**Comment by jhfpereira** [comment]
@cnoss Gilt das für Grafiken und Gemälde?

**Comment by jhfpereira** [comment]
Oder betrifft dies nur die virtuellen Grafikobjekte?

Würde dann `representativeObject` als neues Feld einführen, welches dann nur für virtuelle Grafikobjekte genutzt wird.

**Comment by jhfpereira** [comment]
Change ist mit https://github.com/lucascranach/importer/commit/ec6f65b93af3357aae09214479df2601303511b0 eingeflossen.
JSONs wurden danach nochmal neu generiert.

Kann as Issue somit geschlossen werden?

**Comment by jhfpereira** [comment]
Ok schließe es dann mal, da es korrekt erscheint (aus dem Skype-Gespräch entnommen).
